name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - run: |
         cmd /c cd /
         cmd /c git clone --config core.autocrlf=false -b llvmorg-16.0.1 https://github.com/llvm/llvm-project.git
         cmd /c cd llvm-project
         cmd /c mkdir build
         cmd /c cd build
         cmd /c dir ..
