name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - run: |
         cmd /c cd /d D:\
         cmd /c git clone https://github.com/homasoft/Hello-World.git abc
         cmd /c dir
         ls
         cmd
         ls
         dir
         tree
         ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
