name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          uname -a
          pwd
          git clone https://github.com/homasoft/Hello-World.git
          cd Hello-World
          g++ -Wall main.cpp
          ./a.out
