name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - run: |
         cmd /c cd /
         cmd /c git clone https://github.com/homasoft/Hello-World.git
         cmd /c dir
