name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - run: |
         cmd /c systeminfo
         cmd /c dir
         echo /c set PATH=
         cmd /c set PATH=
