name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install binutils-mingw-w64-x86-64
         sudo apt install mingw-w64-common
         sudo apt install mingw-w64-x86-64-dev
         sudo apt install mingw-w64-tools
         sudo apt install gcc-mingw-w64-base
         sudo apt install gcc-mingw-w64-x86-64
         sudo apt install g++-mingw-w64-x86-64
         sudo apt install textinfo
         sudo apt install flex
         wget https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2
         mv gmp-6.2.1.tar.bz2 gmp
         wget https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.gz
         mv mpfr-4.2.0.tar.gz mpfr
         wget https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
         mv mpc-1.3.1.tar.gz mpc
         wget https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.24.tar.bz2
         mv isl-0.24.tar.bz2 isl
         tar -xvf gmp
         tar -xvf mpfr
         tar -xvf mpc
         tar -xvf isl
         wget https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.gz
         mv gcc-12.2.0.tar.gz gcc
         tar -xvf gcc
         mv gmp gcc/gmp
         mv mpfr gcc/mpfr
         mv mpc gcc/mpc
         mv isl gcc/isl
         mkdir build
         cd build
         ./../gcc/configure --prefix=$HOME/INSTALL --program-prefix= --target=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --disable-nls --enable-languages=c,c++ --disable-multilib
         make all-gcc
         sudo make install
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: $HOME/INSTALL/
          retention -days: 3
